services:

  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


  app:
    build:
     
      dockerfile: ./php/Dockerfile
    ports:
      - "4000:4000"
    # volumes:
    #   - ./app:/var/www/html

  
  db:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

    environment:
      MYSQL_USER: asmaa
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php
volumes:
  mysqldata:

